config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root "home#index"
  get '/team', to: 'home#team', as: 'team'
  get '/careers', to: 'home#careers', as: 'careers'
  get '/contact_us', to: 'home#contact_us', as: 'contact_us'
  get '/portfolio', to: 'home#portfolio', as: 'portfolio'
  get '/testimonials', to: 'home#testimonials', as: 'testimonials'
  get '/matrimonial', to: 'home#matrimonial', as: 'matrimonial'
  get '/shine_brand', to: 'home#shine_brand', as: 'shine_brand'
  get '/legal_properties', to: 'home#legal_properties', as: 'legal_properties'
  get '/it_services', to: 'home#it_services', as: 'it_services'
  get '/import_export', to: 'home#import_export', as: 'import_export'
  get '/contruction', to: 'home#contruction', as: 'contruction'

  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create_mail'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController


def new
    @message = Contact.new
  end

  def create_mail
    @message = Contact.new(message_params)
    
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end


	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def testimonials
  end

  def portfolio
  end

  def contact_us
  end

  def careers
  end 

  def team
  end 

  def matrimonial
  end 

  def shine_brand
  end 

  def legal_properties
  end
  
  def it_services
  end 

  def import_export
  end 


  def contruction
  end 
 end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<section id="contact">
         <div class="container">
            <div class="row text-center clearfix">
               <div class="col-sm-8 col-sm-offset-2">
                  <div class="contact-heading">
                     <h2 class="title-one">Contact With Us</h2>
                     <p>Feel free to contact us.</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="contact-details">
               <!-- <div class="pattern"></div> -->
               <div class="row text-center clearfix">
                  <div class="col-sm-6">
                     <div class=""><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3680.159543484387!2d75.87977441444616!3d22.722310633186225!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3962fd3ed13a2fcd%3A0x9e9f26ad2ee4e40!2sRise+Agro+Infra+Private+Limited!5e0!3m2!1sen!2sin!4v1476038860684" width="100%" height="395" frameborder="0" style="border:0" allowfullscreen></iframe>
                     </div>
                  </div>
                 <div class="col-sm-6">
                     <div id="contact-form-section">
                        <div class="status alert alert-success" style="display: none"></div>
                        <%= form_for @message, :class=>"contact", url: contact_path do |message_form| %>
                        
                           <div class="form-group">
                              <%= message_form.text_field :name, :class=> "form-control", placeholder: "Enter name" %>
                           </div>
                           <div class="form-group">
                              <%= message_form.text_field :subject, :class=>"form-control", placeholder: "Subject"%>
                           </div>
                           <div class="form-group">
                              <%= message_form.email_field :email, :class=>"form-control", placeholder: "Enter email"%>
                           </div>
                           <div class="form-group">
                              <%= message_form.text_area :message, :class=> "form-control", :rows => "7", :cols => "40", placeholder: "Message"%>
                           </div>
                           <div class="form-group">
                              <%= message_form.submit "Send", :class=> "btn btn-primary pull-right" %>
                           </div>
                        <% end %>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="contact-details">
               <!-- <div class="pattern"></div> -->
               <div class="row text-center clearfix">
                  <div class="col-sm-6">
                     <div class="contact-address">
                         <address>
                           <h3>Head Office</h3>
                           <p><span>Rise Agro Infra Pvt. Ltd</span></p>
                           <strong>Address: 315, Third Floor, Princes Business Skypark, A.B. Road, Scheme No 54, Indore Madhya Pradesh 452001<br>
                            Phone: +91 731 2511220</strong><br>
                            Email: riseagroinfra@gmail.com<br>

                            <small>( This our Local addresss situated in madhya Pradesh )</small>
                        </address>
                        <div class="social-icons">
                           <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a>
                           <a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-dribbble"></i></a>
                           <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-6">
                     <div class="contact-address">
                        <address>
                           <h3>Corporate Office</h3>
                           <p><span>Rise Agro Infra Pvt. Ltd</span></p>
                           <strong>Address: #18, Doddaballapur Integrated Textile Park Ltd.<br>
                           SW 51, Apparel Park, Phase II, KIADB Industrial Area, <br>
                           Daddaballapur, Bangalore -561203 Karnataka. INDIA <br>
                            Phone: +91 9406878037, +91 9826729600 <br>
                            Email: riseagroinfra@gmail.com<br>

                            <small>( This is our corporate Office Situated in Bangalore City. )</small>
                        </address>
                        <div class="social-icons">
                           <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a>
                           <a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-dribbble"></i></a>
                           <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

app/views/contact/new_message.html.erb
<% debugger %>
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Name:  <%= @name %></h3>
    <p>
      Email:  <%= @email %>.<br>
    </p>
    <p>
      Subject: <%= @subject %>.
    </p>
    <p>Message : <%= @msg %></p>
  </body>
</html>

app/views/home/contact_us.html.erb
<section id="contact">
         <div class="container">
            <div class="row text-center clearfix">
               <div class="col-sm-8 col-sm-offset-2">
                  <div class="contact-heading">
                     <h2 class="title-one">Contact With Us</h2>
                     <p>Feel free to contact us.</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="contact-details">
               <div class="pattern"></div>
               <div class="row text-center clearfix">
                  <div class="col-sm-6">
                     <div class=""><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3680.159543484387!2d75.87977441444616!3d22.722310633186225!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3962fd3ed13a2fcd%3A0x9e9f26ad2ee4e40!2sRise+Agro+Infra+Private+Limited!5e0!3m2!1sen!2sin!4v1476038860684" width="100%" height="395" frameborder="0" style="border:0" allowfullscreen></iframe>
                     </div>
                  </div>
                 <div class="col-sm-6">
                     <div id="contact-form-section">
                        <div class="status alert alert-success" style="display: none"></div>
                        <form id="contact-form" class="contact" name="contact-form" method="post" action="send-mail.php">
                           <div class="form-group">
                              <input type="text" name="name" class="form-control name-field" required="required" placeholder="Your Name">
                           </div>
                           <div class="form-group">
                              <input type="email" name="email" class="form-control mail-field" required="required" placeholder="Your Email">
                           </div>
                           <div class="form-group">
                              <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Message"></textarea>
                           </div>
                           <div class="form-group">
                              <button type="submit" class="btn btn-primary">Send</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="contact-details">
               <div class="pattern"></div>
               <div class="row text-center clearfix">
                  <div class="col-sm-6">
                     <div class="contact-address">
                         <address>
                           <h3>Head Office</h3>
                           <p><span>Rise Agro Infra Pvt. Ltd</span></p>
                           <strong>Address: 315, Third Floor, Princes Business Skypark, A.B. Road, Scheme No 54, Indore Madhya Pradesh 452001<br>
                            Phone: +91 731 2511220</strong><br>
                            Email: riseagroinfra@gmail.com<br>

                            <small>( This our Local addresss situated in madhya Pradesh )</small>
                        </address>
                        <div class="social-icons">
                           <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a>
                           <a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-dribbble"></i></a>
                           <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-6">
                     <div class="contact-address">
                        <address>
                           <h3>Corporate Office</h3>
                           <p><span>Rise Agro Infra Pvt. Ltd</span></p>
                           <strong>Address: #18, Doddaballapur Integrated Textile Park Ltd.<br>
                           SW 51, Apparel Park, Phase II, KIADB Industrial Area, <br>
                           Daddaballapur, Bangalore -561203 Karnataka. INDIA <br>
                            Phone: +91 9406878037, +91 9826729600 <br>
                            Email: riseagroinfra@gmail.com<br>

                            <small>( This is our corporate Office Situated in Bangalore City. )</small>
                        </address>
                        <div class="social-icons">
                           <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a>
                           <a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-dribbble"></i></a>
                           <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

app/views/home/contruction.html.erb
<section id="home">
		<div class="home-pattern"></div>
		<div id="main-carousel" class="carousel slide" data-ride="carousel"> 
			<ol class="carousel-indicators">
				<li data-target="#main-carousel" data-slide-to="0" class="active"></li>
				<li data-target="#main-carousel" data-slide-to="1"></li>
				<li data-target="#main-carousel" data-slide-to="2"></li>
			</ol><!--/.carousel-indicators--> 
			<div class="carousel-inner slider-mainat-fron">
				<div class="item active" style="background-image: url(../assets/contruction/1-cd80c2d89889287a1103e36b349a98e1d5d0dfeb7fddc9403019bc75c3fd0a5c.jpg)"> 
				 
 -->				</div>
				<div class="item" style="background-image: url(../assets/contruction/2-9b7669f77c3a7fbd6ed9db9e8e918e59c41046875c967477207f1de07b6420d9.jpg)"> 
					 
				</div> 
					<div class="item" style="background-image: url(../assets/contruction/3-f935fd23fdeb63d0c4a94b440d8c9cf6991126daff3c33f546bce1f59918ba62.jpg)"> 
				 
			</div>

				
			</div> 
		
			
		</div><!--/.carousel-inner-->

		<a class="carousel-left member-carousel-control hidden-xs" href="#main-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
		<a class="carousel-right member-carousel-control hidden-xs" href="#main-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
	</div> 

</section><!--/#home-->

<div class="contain-wrapp padding-bot60">	
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="title-head centered">
						<h4>Who we are</h4>
						<p>Inspired is powerful, beautiful, and fully responsive Bootstrap template</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="custom-tabs icon" data-effect-in="bounceInDown">
						<ul class="nav nav-tabs" role="tablist">
							<li class="active">
								<a href="#first2" data-toggle="tab" aria-expanded="true"><i class="fa fa-rocket"></i> Startup</a>
							</li>
							<li class="">
								<a href="#second2" data-toggle="tab" aria-expanded="false"><i class="fa fa-gears"></i> Mission</a>
							</li>
							<li class="">
								<a href="#third2" data-toggle="tab" aria-expanded="false"><i class="fa fa-cloud"></i> Philosophy</a>
							</li>
							<li class="">
								<a href="#fourth2" data-toggle="tab" aria-expanded="false"><i class="fa fa-flask"></i> Target</a>
							</li>
						</ul>
					 
						<!-- Tab panes -->
						<div class="tab-content">
							<div class="tab-pane fade animated bounceInDown active in" id="first2">
								<p>
								We have added this service for information technology. Stared work for website developent in diffrent technologies, Andriod application and iOS application. If you want to digitalize your business we are here to give you best service.
								</p>
							</div>
							<div class="tab-pane fade animated" id="second2">
								<p>
								we are team of Business Analysts, Project Evangelist, Designers, Developers and QAs well versed with bleeding edge technologies, tools and best practices. We began our operations in 2007 with the vision to become an organization that develops partnerships with its clients and adds values to the product.
								</p>
							</div>
							<div class="tab-pane fade animated" id="third2">
								<p>
								We aim to become the leader of Inforation technology world. Innovative high quality products and best services from our teamwork. Become best serive provider in IT Sector for website and App development.
								</p>
							</div>
							<div class="tab-pane fade animated" id="fourth2">
								<p>
								Ex pro vitae maiestatis. Scripta honestatis ad mel, ei alterum detracto consectetuer mea. Erant graecis quo ut, no est minim saperet. An ridens nominati definitionem sed, sit eu appareat qualisque, corpora dissentiunt mea ex. Quot nonumy interpretaris ne ius, quo quod consequat reprimique at. Pri saperet offendit menandri at. Sit et deleniti aliquando. Quis viris dolorem te sed eu lorem aeque viderer eos.

								</p>
							</div>
						</div>
					</div> 
				</div>
			</div>

		</div>
    </div>
    <div class="contain-wrapp gray-container padding-bot50">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="title-head centered">
						<h4>Meet our team</h4>
						<p>Inspired supported by a team of professionals with experience of more than a decade</p>
					</div>
				</div>
			</div>
			<div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <!-- Start Team 01 -->
                    <div class="wrap-team">
                        <svg viewBox="0 0 100 100">
                          <defs>
                            <pattern id="img1" patternUnits="userSpaceOnUse" width="100" height="100">
                              <image xlink:href="images/img02.jpg" x="-25" width="150" height="100"/>
                            </pattern>
                          </defs>
                          <polygon points="50 1 95 25 95 75 50 99 5 75 5 25" fill="url(#img1)"/>
                        </svg>
                        <div class="content">
                            <h5 class="name">
                                Angling darma
                                <small>CO-Founder</small>
                            </h5>
                            <p>
                                Per in purto noster officiis, ferri accusam detraxit no duo vidit vivendum.
                            </p>
                        </div>
                        <div class="share">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram icon-circle fa-primary"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End Team 01 -->
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <!-- Start Team 02 -->
                    <div class="wrap-team">
                        <svg viewBox="0 0 100 100">
                          <defs>
                            <pattern id="img2" patternUnits="userSpaceOnUse" width="100" height="100">
                              <image xlink:href="images/img02.jpg" x="-25" width="150" height="100"/>
                            </pattern>
                          </defs>
                          <polygon points="50 1 95 25 95 75 50 99 5 75 5 25" fill="url(#img2)"/>
                        </svg>
                        <div class="content">
                            <h5 class="name">
                                Loro jongrang
                                <small>Asistance</small>
                            </h5>
                            <p>
                                Per in purto noster officiis, ferri accusam detraxit no duo vidit vivendum.
                            </p>
                        </div>
                        <div class="share">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram icon-circle fa-primary"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End Team 02 -->
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <!-- Start Team 03 -->
                    <div class="wrap-team">
                        <svg viewBox="0 0 100 100">
                          <defs>
                            <pattern id="img3" patternUnits="userSpaceOnUse" width="100" height="100">
                              <image xlink:href="images/img02.jpg" x="-25" width="150" height="100"/>
                            </pattern>
                          </defs>
                          <polygon points="50 1 95 25 95 75 50 99 5 75 5 25" fill="url(#img3)"/>
                        </svg>
                        <div class="content">
                            <h5 class="name">
                                Ken dedes
                                <small>Marketing</small>
                            </h5>
                            <p>
                                Per in purto noster officiis, ferri accusam detraxit no duo vidit vivendum.
                            </p>
                        </div>
                        <div class="share">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram icon-circle fa-primary"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End Team 03 -->
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <!-- Start Team 04 -->
                    <div class="wrap-team">
                        <svg viewBox="0 0 100 100">
                          <defs>
                            <pattern id="img4" patternUnits="userSpaceOnUse" width="100" height="100">
                              <image xlink:href="images/img02.jpg" x="-25" width="150" height="100"/>
                            </pattern>
                          </defs>
                          <polygon points="50 1 95 25 95 75 50 99 5 75 5 25" fill="url(#img4)"/>
                        </svg>
                        <div class="content">
                            <h5 class="name">
                                Aria kamandanu
                                <small>Designer</small>
                            </h5>
                            <p>
                                Per in purto noster officiis, ferri accusam detraxit no duo vidit vivendum.
                            </p>
                        </div>
                        <div class="share">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter icon-circle fa-primary"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram icon-circle fa-primary"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End Team 04 -->
                </div>
			</div>
		</div>
	</div>

 
		
         

app/views/home/create.html.erb
<h1>Thank you for your message.
  <p>
    We'll get back to you as soon as possible.
  </p>
  <p>
    <%= link_to 'Home', root_url, :class => 'button' %>
  </p>
</h1>

app/views/home/import_export.html.erb
<section id="home">
		<div class="home-pattern"></div>
		<div id="main-carousel" class="carousel slide" data-ride="carousel"> 
			<ol class="carousel-indicators">
				<li data-target="#main-carousel" data-slide-to="0" class="active"></li>
				<li data-target="#main-carousel" data-slide-to="1"></li>
				<li data-target="#main-carousel" data-slide-to="2"></li>
			</ol><!--/.carousel-indicators--> 
			<div class="carousel-inner slider-mainat-fron">
				<div class="item active" style="background-image: url(../assets/import/1-0d9e5d78d9d135d4b0a6a31f3597daaa804e93efd94390e08f882a2d68da20ce.jpg)"> 
				 
 				</div>
				<div class="item" style="background-image: url(../assets/import/2-a0727b9853971f8ab8907fb2b805d86af3a803d749275083d83bf03da25c7ecb.jpg)"> 
					 
				</div> 
					<div class="item" style="background-image: url(../assets/import/3-0e053d2ebadd755f0791a704a23fa85ef25a8af5947519107aa1b68003871870.jpg)"> 
				 
			</div>
			</div> 
		
			
		</div><!--/.carousel-inner-->

		<a class="carousel-left member-carousel-control hidden-xs" href="#main-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
		<a class="carousel-right member-carousel-control hidden-xs" href="#main-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
	</div> 

</section><!--/#home-->




    <div class="contain-wrapp padding-bot50">	
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="title-head centered">
						<h4>Who we are</h4>
						<p>Inspired is powerful, beautiful, and fully responsive Bootstrap template</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="thumbnail">
						<img src="../assets/shine/shine2-c5da556c15742e814a89d798802911be3c731a5382b56bd1ac957a621a46baa4.jpg" class="img-responsive" alt="">
						<div class="caption">
							<i class="fa fa-briefcase fa-3x icon-circle fa-default"></i>
							<h5>Solid team</h5>
							<p>
							Ea sea veniam perpetua, ei pro saepe melius. Ex sea summo maluisset. Sit ad adhuc illum epicurei, congue partem qui ne his ad utamur indoctum.
							</p>
							<p><a href="#" class="btn btn-default btn-sm">Learn more</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="thumbnail">
						<img src="../assets/shine/shine3-1ccc2a54401b00c1cce0c129171b6cb0399e4482672040dc1db1f4627e97a536.jpg" class="img-responsive" alt="">
						<div class="caption">
							<i class="fa fa-headphones fa-3x icon-circle fa-primary"></i>
							<h5>Best Service</h5>
							<p>
							Solet praesent et mei. Veniam repudiandae eam eu, ex ius vide etiam dicit. Amet aliquip intellegebat ea pri, oratio sensibus nec id usu vocent.
							</p>
							<p><a href="#" class="btn btn-primary btn-sm">Learn more</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="thumbnail">
						<img src="../assets/shine/shine4-ddeb13f92024e9a81ff272d991f3967d27035764650f26eaf2c83dd4f45d3c0d.jpg" class="img-responsive" alt="">
						<div class="caption">
							<i class="fa fa-flask fa-3x icon-circle fa-default"></i>
							<h5>High loyalty</h5>
							<p>
							Consul dicunt ne mei, usu mutat oporteat senserit ut. Diam cetero audire ex est, sea eu novum choro. Ne fugit noster latine mea  sale apeirian.
							</p>
							<p><a href="#" class="btn btn-default btn-sm">Learn more</a></p>
						</div>
					</div>
				</div>
			</div>

			
		</div>
	</div>


		

app/views/home/new_form.html.erb
<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name, :required => false %>
  <%= f.input :email, :required => false %>
  <%= f.input :message, :as => :text, :required => false %>
  <div class="hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <%= f.button :submit, 'Send message' %>
<% end %>

app/views/layouts/_header.html.erb
<header id="navigation"> 
		<div class="navbar navbar-inverse navbar-fixed-top" role="banner"> 
			<div class="container"> 
				<div class="navbar-header"> 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
						<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
					</button> 
					<a class="navbar-brand" href="<%= root_path%>"><h1><img src="../assets/logo3-7a55b26bf4c5624d7a6a7f622a9c2d6c0184004ac8231e628a50b55fd187e81a.png" alt="logo" style=""></h1></a> 
				</div> 
				<div class="collapse navbar-collapse"> 
					<ul class="nav navbar-nav navbar-right"> 
						<li class="scroll active"><a href="<%= root_path%>">Home</a></li> 
						
					    <li class="scroll"><!-- <a href="#services">Services</a> -->
							<div class="btn-group menuin-dropdown">
							  <a type="" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							    About Us
							  </a>
							  <ul class="dropdown-menu">
							    <li> <a class="dropdown-item" href="<%= team_path %>">Our Team</a></li>
							    <li> <a class="dropdown-item" href="<%= testimonials_path %>">Client Testimonials</a></li>
							     <!-- <li> <a class="dropdown-item" href="#">Latest news&Media</a></li>
							     <li><a class="dropdown-item" href="#">Certificates&Associations</a></li> -->
							   <!--  <div class="dropdown-divider"></div> -->
							    
							  </ul>
							</div>
						</li> 
						<li class="scroll"><!-- <a href="#services">Services</a> -->
							<div class="btn-group menuin-dropdown">
							  <a type="" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							    Services
							  </a>
							  <ul class="dropdown-menu">
							    <li> <a class="dropdown-item" href="<%= matrimonial_path %>">Dhakarmatrimonial</a></li>
							    <li> <a class="dropdown-item" href="<%= shine_brand_path %>">Shine Brand Seeds</a></li>
							     <li> <a class="dropdown-item" href="<%= legal_properties_path %>">Legal Properties</a></li>
							     <li><a class="dropdown-item" href="<%= it_services_path%>">Risedigitech</a></li>
							     <li><a class="dropdown-item" href="<%= contruction_path%>">Construction Work</a></li>
							     <li><a class="dropdown-item" href="<%= import_export_path%>">Import/Export</a></li>
							   <!--  <div class="dropdown-divider"></div> -->
							    
							  </ul>
							</div>
						</li> 
						<li class="scroll"><a href="<%= careers_path %>">Careers</a></li> 
						<li class="scroll"><a href="<%= portfolio_path %>">Portfolio</a></li> 			
						<li class="scroll"><a href="<%= contact_path %>">Contact</a></li> 
					</ul> 
				</div> 
			</div> 
		</div><!--/navbar--> 
	</header> <!--/#navigation--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riseagroinfra Pvt Ltd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= render :partial => 'layouts/header'%>
<%= yield %>
<%= render :partial => 'layouts/footer'%>

</body>
</html>